### ISSUE TITLE
Authors component styling 

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#1046]
## Description
For publications, we can supercharge the authors component and give it a professional sheen. Shea has already mocked up how these look in the blog pages. Adding this sophistication sitewide would be awesome. 

### Tasks for publications:

- [ ] Add the circular image cap on top of the square image pulled from `all-contributors` 🤖 
- [ ] Display just the name 
- [ ] hover and link inside each displayed author takes them to the GitHub profile (for now)

### Tasks for authors component: 

Beyond publications, using the <authors> module/component on the contribute page is a content creator need  (see #1042 ). 

- [ ] authorRenderer and gridcell overlap to display authors in the correct grid. especially for mobile shrinking down to displaying just one. 
- [ ] have a full width `<authors all/>` set to `display=4`  in rows 
- [ ]  mobile `display=1` just like [shea's style](https://www.figma.com/file/7aKYK8Z5dzL7WN6PJYsmwV/Maker-Comm-Dev-%E2%80%93-Blog?node-id=3054%3A6680)

**Comment by MaximumCrash** [comment]
Closed by #1172
