### ISSUE TITLE
Hackathon Section Improvements Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#124]
- **What:**
  - Need to work on IA, understand what pages need to be in the menu.
  - Quickstart: You're a hacker vs you're an event organizer
  - Event organizer: 
    - [Hackathon template](https://docs.google.com/spreadsheets/d/15PI5myDV48Vl1jVgtwHrm2KT4oB1WXBSolknf1FXlyg/edit?usp=sharing)
    - [Hackathon Winner to grantee supporting information](https://docs.google.com/document/d/1S4eUBTL5dsBbmdeS0XLleC71sOg7EDJD3EKliAJGvUI/edit): needs conversion to airtable
    - [Funding Requirements](https://github.com/makerdao/community/blob/master/hackathons/requirements.md): needs cleanup
  -   [Engagement Calendar]
- Hackathon Participant:
    - content?
- **IA:**
  - [x] [Hackathons Landing Page](https://hackmd.io/TdTXQRAMRt2M0TGjRb8MDA?edit)  (PR Submitted)
    - [x] [Quickstart (Developer)](https://hackmd.io/Wz8gL7JGQQKGou8cXBWyQQ) (PR Submitted)
    - [x] [Quickstart (Organizer)](https://hackmd.io/Ke630nyPSyOQt96bjvvaqQ) (PR Submitted)
    - [ ] [Idea Board and featured projects(can be added after MVP)](https://hackmd.io/RLb6IvIgSTe41D99EJMEZw)
    - [ ] [FAQ](https://hackmd.io/HCMHVAjyTCWAHLil7GdCTA)

Tasks

- [ ] Task 1 / ?

**Comment by Davidutro** [comment]
Created HackMD docs (Drafts). Working on them now. 
Deadline Wednesday 7/10 for all of them.

  - [ ] [Hackathons Landing Page](https://hackmd.io/TdTXQRAMRt2M0TGjRb8MDA?edit)
    - [ ] [Quickstart (Hacker)](https://hackmd.io/Wz8gL7JGQQKGou8cXBWyQQ)
    - [ ] [Quickstart (Organizer)](https://hackmd.io/Ke630nyPSyOQt96bjvvaqQ)
    - [ ] [Hackathon FAQ](https://hackmd.io/HCMHVAjyTCWAHLil7GdCTA)

**Comment by Davidutro** [comment]
Update: 
  - [ ] Hackathons Landing Page: Draft done
    - [ ] Developer Quickstart: Meeting with Vamsi tomorrow 3pm EST to complete it. MVP draft is finished
    - [ ] Organizer Quickstart: Working on draft, might need to make airtable to maker it easier for Organizers to contact us with all relevant information
    - [ ] Hackathon FAQ: May need to be split into two docs (Developer FAQ vs Organizer FAQ)

**Comment by Davidutro** [comment]
Additional idea:

Page to track past hackathon winners/projects can double as an idea board. 
We want to have a place where all outstanding ideas for hackathons live.

I imagine it could be something like this: 

| Idea | Projects |
|Create Governance Data Dashboard|Project 1:[Devpost](link): other link to relevant info|
|-----------|---|

**Comment by ghettodev** [comment]
Let's break this ^ out so we can close this ticket soon

**Comment by amy-jung** [comment]
Archived.
