### ISSUE TITLE
Governance Section Improvements Epic

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#125]
The primary landing page for the [Governance section](https://github.com/makerdao/community/blob/master/governance/README.md) should be a clear one-pager on what Governance is all about and should provide some context about the resources available. 

Nice to haves: 
- [ ] Tooling: dashboards, scripts, portal
- [ ] Howto: voting, debating, communicating
- [ ] Create governance onboarding guide
- [ ] Governance meeting roll-ups: video, audio, transcript, summaries, etc on single per episode page
  
IA:

  - [ ] Readme/landing page(#237)
    - [x] Core Foundation Principles   
    - [x] Governance Risk Framework pieces
    - [x] Onboarding Voters (#238)
    - [x] Governance and Risk Meetings (summaries and transcripts lives within)
    - [ ] Archive (contains useful threads, old conversations, older governane resources)
    - [x] FAQ (can link to the existing Governance FAQ)

**Comment by Davidutro** [comment]
Should I create a separate issue for improving the Governance Landing page (and other pages individually)?

Is it that whoever picks up a task in this issue creates their own issue and makes this issue dependant on theirs?

**Comment by ghettodev** [comment]
I just made a few of the "X Section Improvements" tickets into Epics. I think we can just make new tickets and ensure that they are linked to the right epic?

**Comment by ghettodev** [comment]
Resources from UX https://www.notion.so/makerdao/Community-Development-x-User-Research-507dac9ff86d48f7b8a334e6c9a04b3b

**Comment by LongForWisdom** [comment]
I'd like to create a summary of the major governance topics that come up as part of the governance conversation. I feel like this could help on-board voters and give outsiders an idea of what exactly we spend our time debating, hopefully giving them some idea of whether they would be interested.

This would include:
- Stability
- Security
- Growth
- Financials
- Tooling
- Upgrades
- Payroll

I think this covers most of the major topics that are discussed. For each I can write a bit about what is discussed and why it's important.

**Comment by LongForWisdom** [comment]
I have created a first draft of this page. Feel free to leave feedback here: https://docs.google.com/document/d/1OtwLCSVpfwc-0Y9N7JRd8_BSWvtqlbuvw-JNHvMnn2s/edit?usp=sharing

**Comment by amy-jung** [comment]
Other from @LongForWisdom:

- [ ] Write up of CMooney's instructions on how to audit executive spells. (https://forum.makerdao.com/t/how-to-audit-executive-contract-code/1292/3)
- [ ] Write up of all the parameters that governance is able to change, with descriptions and the trade-offs surrounding changing them in various ways. (Ideally divided by area)

**Comment by Davidutro** [comment]
This issue is outdated due to the new commdev portal.

The governance pages have been rethought and we are in the process of improving them for the V1 launch of the portal and will continue to improve them as the portal is maintained and further developed.

I am closing this issue, this same initiative will be captured in on a newer issue to improve those pages.

**Comment by Davidutro** [comment]
Updated issue:
#761
