### ISSUE TITLE
Italian - FAQ Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#163]
Original document: https://community-development.makerdao.com/faqs

- [ ] [Glossary](https://github.com/makerdao/community/blob/d6d6d3ec5ebec816ef5dc2ea00b28a83463eb59b/faqs/glossary.md)
- [x] CDPs FAQ
- [x] Dai FAQ
- [ ] Emergency Shutdown FAQ
- [x] Governance FAQ
- [ ] Keepers FAQ
- [x] Liquidation FAQ
- [ ] MakerDAO FAQ
- [ ] Oracles FAQ
- [ ] Risk Management FAQ
- [x] Stability Fee FAQ

**Comment by amy-jung** [comment]
These are SCD - closing since we will create new tickets with MCD versions.
