### ISSUE TITLE
Maintenance Plan Q1 2020

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#198]
The maintenance plan presents opportunities for community members to update and maintain MakerDAO's public set of community resources.

## Working Docs
- [Q1 Spreadsheet](https://docs.google.com/spreadsheets/d/1x1VKG3eb5aRg6CvC5XUgG_AngA_Qas7dYcOqBEgWN1A/edit?usp=sharing)

## Tasks
- [x] Assign rows to contributors
- [x] Review PRs
- [x] Merge all PRs
- [x] David does a final check to conclude this quarter

**Comment by Davidutro** [comment]
Thoughts on the `who`: 

- Would make sense to report up-to-date info on the initiatives to Rich at the end of each quarter maybe? Then have Rich update the JSON files.
- Everything else (listed below) could be done by me, or portions can be outsourced via bounties to community members

Thoughts on the `what`: 

- Updating information in the JSON files that populate the transparency dash/status sections
- Auditing the links, adding and replacing them as needed
- Updating information on closed initiatives or changed requirements & processes

Thoughts on the `when`: 

- Quarterly is a good cadence imo.
- Every 3 months David reports to Rich the stats for each initiative. (Rich updates the JSON files)

**Comment by ghettodev** [comment]
Another thing we need to promote is the idea of self-reporting changes. i.e. Hackathon winners can follow instructions on how to add themselves to certain pages.

**Comment by amy-jung** [comment]
Kicking into gear now: @Davidutro and I started a sheet for action items

**Comment by Davidutro** [comment]
Moved this to an issue, created a proper maintenance plan Epic #510
