### ISSUE TITLE
Awesome-MakerDAO Epic

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#214]
Awesome-MakerDAO is a community-curated list of MakerDAO-related resources and content to which anyone can contribute.

[Project Planning Doc](https://hackmd.io/UGAkkqWTQv-a7Gsz2yRfyw)

Goals
- [x] Documents and links need review and cleaning up / #361 
- [x] Develop clear criteria around adding/deleting resources / #363
- [x] Tie into the [main maintenance plan](https://hackmd.io/v2E4yba1S_O-b2hgnHYw-Q?both) / #362
- [x] Integrate [bounties](https://hackmd.io/z__nbzNBSuibsBzswsQUkQ?both#Bounties-Project-Planning-GROWTH) / #364

**Comment by ghettodev** [comment]
Let's sit down and have a deep discussion before anyone starts work on this, lot's of previous history to catch up on.

**Comment by amy-jung** [comment]
Planning doc: https://hackmd.io/UGAkkqWTQv-a7Gsz2yRfyw

**Comment by aburban90** [comment]
Hey... so... @Davidutro @ghettodev @amy-jung 

Looking over the various AMD's floating around. 

The current Live version: (Updated Dec 3, by @jpgonzalezra)
https://github.com/makerdao/awesome-makerdao/blob/master/README.md

Latest HackMD (V1.1): (Updated Dec 5, by @Davidutro) (These came later, but somewhat diff from the latest merge)
https://hackmd.io/TARaxB0dRJGf53xmU2GBQw?both

I'm trying to make sense of which edits supersede which...

Looking to make a fresh-doc that will be V1.2 or something of the sort
Somehow get everyone who wants to update to main, update to hackmd, and we merge the changes as we go?  (Maybe with some regular cadence... monthly?)

Reason I want to do this... atm, have the latest changes all in one new doc... and from there, build out a maintenance plan doc

**Comment by aburban90** [comment]
Okay, above comment resolved:

New Working AMD HackMD:
https://hackmd.io/gI0qUOvCS5mlsMin9wAo-g?both

**AMD Maintenance Guide**
[Working AMD Maintenance Doc: V0.1](https://hackmd.io/O8BbsEH8QUy7grdJ4duekQ)

**Comment by aburban90** [comment]
So, I think this maintenance guide is ready for review.
At least, for fresh set of eyes

**Comment by Davidutro** [comment]
@aburban90 took a look, good stuff. You got A LOT done. I only briefly looked through it.

I added some stuff in the new AMD draft doc under Governance. I think it's important to think about the information we present here. What information would be useful here to someone jumping in from 0, and what information would be good here for an outsider to come in and see some of the essential resources that need to be seen before jumping into maker governance
