### ISSUE TITLE
Portal EPIC: Move Gitbooks into a different Content Management System

### ISSUE THREAD

**Issue by ghettodev** [makerdao/community#225]
There are some limitations to the gitbooks implementation that we can’t get around. Community Development would like someone to create a new framework for us with docusaurus that basically looks and behaves exactly like the existing portal.

[Working Doc](https://hackmd.io/@rawhaus/SkGcspKir/edit)

**Criteria:**
- searching with algolia or equiv
- easily maintained css
- should sit in the same repo as the existing content?
- or can we set up a new repo that ingests content from the primary repo?

https://forum.makerdao.com/t/wanted-a-docusaurus-setup-to-replace-the-existing-portal/149

**Comment by scottrepreneur** [comment]
I started this here with some outstanding questions.
https://github.com/scottrepreneur/maker-community#questions

**Comment by amy-jung** [comment]
@scottrepreneur : adding original problem with Gitbooks:

- Every link in the body of the text needs to exist in the left nav or it is replaced with a github link
- Inability to embed arbitrary code (limits our ability to include transparency dashboard)
- Limited theming options
- No LaTex, it converts everything to json in its side and messes with formatting

**Comment by amy-jung** [comment]
Migration script blockers answered here: https://hackmd.io/Td-PoJUBTi61cs3PHKDKYw?both

**Comment by amy-jung** [comment]
Tasks:

- [x] Scaffold
- [ In progress ] Update community repo and transform script
- [ ] Community repo: add headers to all files, move README to top level files update links to those top level files
- [ ] Transform: API ping?, clone into new repo into ‘docs’ directory, remove unneeded headers
- [x] Implement search - algolia plugin - update API Key once live and crawled
- [x] Sidebar for meeting summaries and transcripts is separated because submenus are not collapsable in v1
- [ ] Implement translations with CrowdIn
- [x] Implement config adjustment to remove ‘docs’ from URL
- [x] **Implement Edit on Github
- [ ] Design and implement ‘Landing’ page
- [x] Check for broken links
- [ ] Design Finishing
- [ ] Plan for migrating into Docusarus 2
- [ ] Maintenance plan

**Comment by amy-jung** [comment]
This initiative is put on hold until the end of the year.

**Comment by scottrepreneur** [comment]
The first iteration of Docusaurus v1 is done.
https://github.com/scottrepreneur/maker-community

**Comment by twblack88** [comment]
New Gatsby powered CMS migrated on 10-6.
