### ISSUE TITLE
Create Onboarding major section in the Portal Epic

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#240]
**Status:** Section does not exist yet
**Type:** Educational
**Notes:** We should launch this only once we have all 3 of the MVP guides for this section. Then we can add other guides later.

[Planning Doc](https://hackmd.io/PgIr2M8_RkiEuBxLXcVRrw?edit)

Goals:
  - [x] Landing Page (#248)
  - [x] Onboarding guide Voters (#238)
  - [x] Onboarding guide Dai users (#253)
  - [x] Onboarding guide CDP users (#252)
  - [ ] Onboarding guide Keepers
  - [ ] Onboarding guide Auctions
  - [ ] Onboarding guide ??? (GIVE US SUGGESTIONS!)
  - [ ] FAQ / Do we need an FAQ? I'm not convinced we do - David

### Older Onboarding Resources

- [Scott's Dai onboarding start](https://docs.google.com/document/d/1FQ9RpSsC8KEsif5LHlwWfO8SKkNHc3rFH8FaFDfgHfk/edit#heading=h.4kqvye4zs81j)
- [Scott's CDP onboarding start](https://docs.google.com/document/d/1-U5dcb19v3y9rHbbHXHjO48bKDPU9V5xfIYlXG1g06E/edit#heading=h.x0krh5qqdl6m)
- [Sendwyre onboarding guide](https://drive.google.com/open?id=1gkpJnb3WGaFsZC3pOKjMynPDNBM-twzb)
- [Hoffmans guide](https://drive.google.com/file/d/0B1OTGaeknyLqNlNCb3UxQU9zZ0owWWhuZXBJUWZzQUNERDY0/view?usp=sharing)

**Comment by Davidutro** [comment]
What onboarding guides do we want?

- Voter Onboarding
> Straightforward, but do we want to create this for SCD or MCD? I feel like this onboarding would need to walk users through the process of becoming a voter through the current GUI. 
- Dai User Onboarding
> I imagine this would be something like introducing people in various Jurisdictions how to acquire Dai, and then an introduction to all its use cases and even showing them where they can access dapps.
- CDP User Onboarding
> There are several guides, made by the community, already available, how is this one going to be different/stand out as effective and useful?
- Tooling Guide? 
>this needs to be elaborated upon further, also a high likelihood that it becomes obsolete fast and often
- Risk Team Onboarding Guide
>This would live under the governance section? or would it be better under this section? Also, there is no foundation for this as no Risk Teams have been "Onboarded" per se. This is an idea for a guide that will eventually live in this section.

Contributing section contains 
- [Style Guide ](https://community-development.makerdao.com/contributing/style-guide)

**Comment by Davidutro** [comment]
added older onboarding resources to top-level comment

**Comment by amy-jung** [comment]
Some are good to go by next week Thursday. 

Maker Figma UIs would be better replacements for screenshots (ping Jordan)
@Davidutro will convert to hackmd and @ghettodev will review next week.  

We should be using links from making asset directories in Github repo instead of relying on IMGUR

"Why should I vote" should be brief answer for now. Eventually be a page on Governance section.

**Comment by Davidutro** [comment]
Keeper Onboarding Guide -- hit up CMooney

**Comment by Davidutro** [comment]
Closing this issue.

Onboarding has become "Work with us" in the new comdev portal.

#561
