### ISSUE TITLE
Streamline Bounties Workflow Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#264]
Bounties act as a workflow tool as well as incentivizing community contributors. Bounties also provide a way to delegate and scale the work required in the MakerDAO community's resources.

[Project Planning Doc](https://hackmd.io/@rawhaus/S1oSHdh9H)

Goals

- [ ] Gather data and requirements / #358 
- [ ] Standardize operation procedures / #359 
- [ ] Create a page in the contributor section for microbounties / #360

**Comment by amy-jung** [comment]
Current explorations: https://docs.google.com/document/d/1Tklm-VSbt3b4sId5_XwSp_KJK4itSGCjVvjEbN1FdVU/edit?usp=sharing

**Comment by amy-jung** [comment]
Spoke to Bounties Network - will need to spec out what we want to bounty:

Current assessment:
1. Works for small, quick needs like "clean up files"
2. Too much of a process commitment for a large project like Translations
3. Redesigning their interface will require a lot of work

Also to consider: With Bounties Network we will need to lock up some funds

**Comment by amy-jung** [comment]
Open question: How do we get updates about juicy bounties (Mailing list, twitter bot, etc)

**Comment by amy-jung** [comment]
Had a conversation with Simona Pop about a potential bespoke version of a soon to be launched bounties network

**Comment by Davidutro** [comment]
@amy-jung should we close this issue?

**Comment by amy-jung** [comment]
Closed, as we stopped using bounties: [Archive of the project](https://hackmd.io/aZ0JxBNNTPOB__9_ul23Rg)
