### ISSUE TITLE
Translations Project Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#341]
As MakerDAO and Dai spread across the world, our focus is on creating universally accessible resources. Through the Translations Initiative, we are working to grant wider audience access to materials about MakerDAO in their native languages.

[Planning document](https://hackmd.io/@6u9ugGbWSKq4MIEiDa499A/ByG7u2d9S)

Goals
1. [ ] #347 | Data & Requirements gathering
_includes "Come up with measurements for utility & ROI"_
1. [ ] #350 | Figure out if the current process is working and how we can make it better.
1. [ ] #348 | Establish a public MCD-centric inventory list for resources available for translation by special request.
1. [ ] #349 | Develop best community-integrated strategy to choose the next translated content

**Comment by amy-jung** [comment]
- [ ] Gather Data (Google Analytics and Community Managers) & Requirements
- [ ] Define success measurements
- [ ] User test
- [ ] Determine MCD-centric resource inventory list

**Comment by Davidutro** [comment]
Added issues for the subtasks of this epic. Currently adding info to the top-level comment in each issue.

**Comment by Davidutro** [comment]
MCD FAQ translations are still on pause. 

The next step is to do a review/audit of the FAQs in order to polish them in English before they are actually translated. 

A nice to have is to complete the release of the rest of the FAQs and review those as well. Since having everything ready will make it a lot more efficient for the community to translate.

**Comment by amy-jung** [comment]
This project has been deprecated, but archived.
