### ISSUE TITLE
Establish public Inventory list for English resources available for translation by special request

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#348]
### General Overview

- [x] Determine MCD-centric resource inventory list
    - [x] Spend 10-20 minutes reviewing the inventory list below
- [x] Define primary stakeholders
- [ ] Get community manager input on the inventory list

#### MCD-centric resource inventory list

Original Content Inventory is [found here](https://hackmd.io/kpjDvDVIQaS5aPwb8PPKhQ?view#Translatable-Content-Inventory)

- Spend 10-20 minutes reviewing 
_This task will be open for a while.  I invite as many people as possible to add to and refine the [MCD Translatable Content Inventory](https://hackmd.io/kpjDvDVIQaS5aPwb8PPKhQ?view#Translatable-Content-Inventory-MCD-Centric)_
- We need to think of where this would live.
_my proposal is that it lives in this repo: https://github.com/makerdao/community/tree/master/translations_

#### Define primary stakeholders

insert

#### Get community manager input on the inventory list

We can present a call to action for them during the initial call. We then need to follow up with them during user testing. This is covered in issue #349

The working doc for requesting translations can be [found here](https://hackmd.io/IKQG20bURKasy5RuFj-wuQ?view).

### Tasks

- [ ] Task 1 / Define criteria for accepting a translation job
_As of now, it's Rich's discretion and approval_
- [ ] Task 2 / Add the inventory list to the public Github somewhere
_I suggest adding it as its own page within the section, but before doing so we need to understand who can request from the inventory and what the criteria is for acceptance_

**Comment by Davidutro** [comment]
Needs discussion, can be useful for Translation program efforts.

**Comment by amy-jung** [comment]
embedded in the new portal
