### ISSUE TITLE
Transparency Dashboard V2 Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#390]
## Description
The Transparency Dashboard is a resource for displaying the KPIs and statistics for Community-Development initiatives.

[Project Planning Doc](https://hackmd.io/rGoz8zqESkqKrsuydlweZA)

## Goals

- [x] Clean up current code base, bugs
- [x] Grants Transparency Dashboard
- [ ] Translations Transparency Dashboard /  #157 
- [x] Meetups Transparency Dashboard / #156 
- [ ] Hackathon Transparency Dashboard / #200

**Comment by amy-jung** [comment]
Closing as we decided not to pursue a Translations & Hackathon Dashboard. Grants and meetups are complete.
