### ISSUE TITLE
Communications Plan for Meetup Grants Program

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#392]
## Description

To make the DIY Meetups & Microgrants program successful, we need to market it like anything else. It's a free tool for our community and the communications of this program should be planned and executed in order to produce results.

[Communication Plan](https://docs.google.com/document/d/1emeIPA0tuQj7EZdo8EWOcVs-U0rlZQCSAapN9aMgPQQ/edit#)

## Tasks

- [x] Task1 / Craft clear marketing/communications strategy around this program [(see this section)](https://hackmd.io/06o_0H0WRuy9_Y3e8IIMPQ#Craft-marketingcommunications-strategy)
- [x] Task 2 / Craft an inventory messaging that captures the vision of our program.
- [ ] Task 3 / Create a timeline and execution strategy.
- [ ] Task 4 / Talk with Coulter and community managers about getting on board.

**Comment by Davidutro** [comment]
This is up to date, need to get on this in the coming days.

**Comment by Davidutro** [comment]
The plan was partially complete and followed. Now the meetup program is set to wind down in the coming months so I am closing this and related issued out.
