### ISSUE TITLE
MCD FAQs V2

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#403]
## Description

V2 will involve bounties that incentivize the community to offer suggestions and improvements to these docs. A series of bounties will occur in line with the V2s. Currently, we are thinking whether to do one at a time, 1x per week, or batches of 2-3 FAQs per week so we can get through this review process relatively quickly. I, David, am leaning towards doing these bountied reviews in batches.

Epic: #324 

## Tasks

- [ ] Task 1 Before anything happens, release remaining v1 MCD FAQs
- [x] Task 2 Create [Sample Bounty](https://hackmd.io/X-S_X9fJSqm0mgDEpLsYFw)
- [ ] Task 3 Go over [Jordan's community feedback research](https://www.notion.so/makerdao/Community-feedback-b293eede5a0d4b1d8b0d10821935d780) for additional questions we can add for the V2

## Bounties

- link when they are live

**Comment by Davidutro** [comment]
Plan is to include this as part of Q2 Maintenance Plan

**Comment by Davidutro** [comment]
outdated, replaced by learn section pages.
