### ISSUE TITLE
Create a "CDIP" page in the Contributing Section

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#421]
## Description
The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

[Project Planning Doc](https://hackmd.io/@rawhaus/rJX6JE3jH)

Contributing Section Epic #158 

## Tasks

- [x] What is a CDIP
- [x] CDIP workflow process explainer (how to submit a CDIP and what next steps are)
        - Entire flow from submitting proposal to executing (Image)
        - "Dos & Don'ts" there is a limited number of projects per contributor and an example of what a project cost could be (guardrails), resources should be written together if there are predetermined contributors (just need 1 CDIP for all contributors who are involved and they should work together to figure out the scope
- [x] CDIP template
- [x] Current list of CDIP and their statuses

**Comment by twblack88** [comment]
Working doc: https://docs.google.com/document/d/1a8ZPqNHMUde0oHa2XvCJwUjWsMd7L6wEJ54UsDEL0uw/edit

**Comment by twblack88** [comment]
Currently "list of CDIPs" depends on CDIP page. We're evaluating the best way to do that here on github

**Comment by twblack88** [comment]
up on this branch: https://github.com/twblack88/community/blob/TimB-test/contributing/README.md
