### ISSUE TITLE
CDIP 7 - DAI-gest

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#431]
Title: Weekly Governance Recap

Your name/handle: Adrian Hacker @adrian h

Links to Github issue/forum post/ or discussion thread: 

https://forum.makerdao.com/t/wanted-weekly-governance-recap-for-mkr-holders/688
personal repo: https://github.com/adrianhacker-pdx/MKR-holder-DAI-gest

Proposal abstract: Writing the weekly governance recap.  Concise statistical data of Dai/Sai/Mkr.  Values, Peg, Circulation, Stability fees, savings rate, circulation stats, debt ceiling stats.  Information as Sai is being phased out.  Direct links to governance meetings.  Concise bits about Dai, how to become involved, cool apps that use Dai.  Links to articles.  Geared towards Mkr holders, but also written to inspire curiosity in non-Mkr holders.  To be posted on Reddit / Medium / (?)

[CDIP 7](https://docs.google.com/document/d/1tudqXoOOWvZfHJc7MTvT7AsBtKKW2Rembqg7JgiIDEs/edit?usp=sharing)

## Tasks

- [x] Committee review
- [x] Standardize review process for recap using our documentation framework. (assign editor and approver)
- [x] QA next update

**Comment by twblack88** [comment]
https://docs.google.com/document/d/1tudqXoOOWvZfHJc7MTvT7AsBtKKW2Rembqg7JgiIDEs/edit#
Adrian will be writing a newcomer friendly and Maker stakeholder friendly weekly governance recap. With stats, info, links, and stories. We have a [90 day roadmap](https://docs.google.com/document/d/1fVxAgt_6NdDg-ctGOxiSQuQdur25jFYWTg5IWZwaMxE/edit) to source more contributors and quality controls, analytics, and community lead iterations.

**Comment by twblack88** [comment]
- [ ] Adrian to develop norms and a team around editing. The community, (mitote, longforwisdom, other contributors on the forums like SamM or MakerMan, reddit etc.) will be reviewers. 
- [ ] adrian will host canonical updates on github and distribute to his own channels.
