### ISSUE TITLE
CDIP 1 - Oasis Walkthrough video(s) for MCD

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#432]
**Title:** Oasis Walkthrough video(s) for MCD

**Your name/handle:** @reuptaken

**Links to Github issue/forum post/ or discussion thread:** SCD version of walkthrough videos was quite popular (2.5K views English version, 1.2K views Spanish version, 0.1K views Polish version)

**Proposal abstract:** The goal is to create 1-3 videos with step-by-step explanations of how to use all Oasis websites (similar to: https://www.youtube.com/watch?v=jQoBIVssz2s). The format used will allow to easily translate and record voice-over in any language.

[CDIP 1](https://docs.google.com/document/d/1o6UgXsZbaNyWB_x-l4_1_Hk7ahq-yrbYRlCrKho8l7Q/edit?usp=sharing)

## Tasks

- [x] Finished Polish version of video(s)
- [x] Keynote/source version of video(s)
- [x] English text (which has to be edited by some native speaker)
- [x] Directions on how to create international versions of video (in English)

To prepare the English version of the video additional steps needed are:

- [x] Editing of English copy (by someone with some MakerDAO knowledge, 2-3 hrs)
- [ ] Recording (this can be done by anyone with good reading skills, and takes 1 - 1.5hrs max)
- [ ] Sound editing and synchronization (by me or someone else, 2-3hrs)

Creating videos in other languages involves similar steps (step one will require translation from English and can take longer time)

**Comment by amy-jung** [comment]
Decided to skip 30 minute kickoff meeting since it was fairly straightforward and @reuptaken is seasoned in this section

**Comment by amy-jung** [comment]
Setting up a 30 min meeting Friday 2/7 with stakeholders (Rich, Shepherd, Owners) to go through details of the work/ key stakeholder sign off to move into the next round

**Comment by amy-jung** [comment]
**Next Steps:** 
Tom - will go through the script and edit as necessary then we'll all resync before handoff any potential video edits to @reuptaken

**Comment by amy-jung** [comment]
@ghettodev The English step by step is ready for your review. We're holding off on more edits to video or Polish version until you give the ok.

https://docs.google.com/document/d/1jq2QLuYQpZcjnnD35vCMxsbrCOgj6DZGgicfrDYPtBM/edit#heading=h.wz87b6wt1xdz

**Comment by ghettodev** [comment]
added my comments. looks really good.

**Comment by reuptaken** [comment]
Thanks! I answered a few of them and I hope Tom will handle the rest.

**Comment by amy-jung** [comment]
https://www.youtube.com/watch?v=GjMI_1zkBzo&feature=youtu.be
