### ISSUE TITLE
CDIP 5 - MakerDAO Grants Transparency Dashboard v1.5 Refactor

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#434]
**Your name/handle:** @asterix

**Links to Github issue/forum post/ or discussion thread:** https://github.com/makerdao/commdev-grants-transparency-dashboard/issues/1

**Proposal abstract:** Rich has expressed an interest in expanding the Transparency Dash to include metrics for other aspects of Maker’s community initiative, such as hackathons/meetups.

There are some additional features that Rich also wants to see implemented in the current design. Before tackling these, it would be best to refactor the existing code to improve the foundation upon which these updates will be made. 

## Tasks

- [x] Refactor Code (components, pages, theming/stylesheet)
- [x] Update JSON object to include Audit link for Audited projects
- [x] Add empty state for project categories w/o a grantee

[CDIP5](https://docs.google.com/document/d/1Hff-vX_dbSHP7CrMUWY8IfnhQmp_jreZX0VXf7XUDXs/edit?usp=sharing)

**Comment by amy-jung** [comment]
**Approval:** [ ✅ (good to go)], Amy Jung (+Rich, David, Tim), 1/27/2020

Approved for execution since it would be solving some technical debt + laying foundations for generic

**Comment by amy-jung** [comment]
Update Feb 5: Project is halfway through.

**Comment by as-dr** [comment]
Update: Refactor is complete and the PR is ready to be merged, once I've run through it with @ghettodev

**Comment by amy-jung** [comment]
PR has been merged by Rich
