### ISSUE TITLE
Meetup Grants Pivot to Virtual Meetups

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#495]
## Description

Due to the extended nature of COVID-19, we are expanding the scope of the meetups program to include a larger emphasis on virtual meetups.

## Ideas

- Put out a special call-out for virtual meetups done in non-english languages?
- Attend a couple to understand what works, what doesn't, etc. For better general insights.

## Tasks

- [x] Task 1 / Go through the meetup program front page and add elements that emphasize virtual meetups
- [x] Task 2 / Update Format Guide to include virtual meetup section (might take the form as its own issue, and I will give it to a contributor to do.)
- [x] Task 3 / Update FAQ to include virtual meetup related questions
- [x] Task 4 / Update Marketing Plan to include some set of messaging about virtual meetups.
- [x] Task 5 / Define specifically what we are funding in regards to virtual meetups in the requesting-funds.md page
- [ ] Task 6 / Create presentation around Meetups Program (will be presented on the Wednesday standup and also to the Community Leads on the June 03rd call)

**Comment by Davidutro** [comment]
Brainstorm:

Idea for a Virtual Meetup Guide: This would be a guide with ideas for the format of a virtual meetup.

We already have the Event Formats Guide. Should Virtual meetups exist as a section inside of that guide?

Argument for yes:
It's just another type of format, so semantically it makes sense.
Combining it would result in less pages(noise) without losing much in discoverability.

Argument for no:
Virtual Meetup funding is an odd thing that might deserve it's own guide. 
It would need to be more than a format guide if it lives alone.
The first question that comes to mind is "What exactly are you funding?" So pointing people to the answer might be important enough to include inside of this. However, it can also be included as a question in the FAQ or in the requesting-funds.md page.

**Comment by Davidutro** [comment]
Fixed the application form on airtable to include options and info for Virtual meetups

**Comment by Davidutro** [comment]
Updated the Event formats Guide with "A Note on Physical versus Virtual Formats"

**Comment by Davidutro** [comment]
Added FAQ question: "What is a Virtual Meetup?"

**Comment by Davidutro** [comment]
added **Task 6 / Create presentation around Meetups Program (will be presented on the Wednesday standup and also to the Community Leads on the June 03rd call)**

**Comment by Davidutro** [comment]
cool VR game platform where meetings can be held:
https://somniumspace.com/

(VR and PC only so it's limited for now, but might be great for another option for an online event venue.)

(adding this here so it doesn't get lost, I want to add it to the VR Event guide that will eventually exist.)

**Comment by Davidutro** [comment]
We did pivot, and will continue to do so. Closing this issue as it is complete in principle. 

This issue existed to accelerate this pivot when COVID happened. Now that we have, it's just a matter of continuing to focus on this line of meetups in our documentation, content, and communications plan for the program.
