### ISSUE TITLE
Contributing Section V2 Epic

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#503]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Working or Proposed Project Doc: Not Started

## Goals

- [x] CDIP Explainer V2 #504 
- [ ] Contributor Onboarding Guide V2 #505 
- [x] Earn as a Contributor V2 #506 
- [ ] Contributing Section FAQs V3 #507
- [x] Contributor Tools Guide V2 #508
- [ ] Visual Style Guide V2 #509
- [x] All-Contributors Page #522

**Comment by Davidutro** [comment]
Referencing this issue in #762 to give the contributing section an issue to look back at for ideas
