### ISSUE TITLE
Contributing Section - CDIP Explainer V2

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#504]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Contributing Section V2 Epic #503 
Working or Proposed Project Doc: Not Started

## Tasks

- [ ] Check for healthy cross-linking, obsolete information, typos
- [ ] Add Auto-updating table of CDIPs

**Comment by twblack88** [comment]
Outstanding tasks here:

- [ ] Last round of Feedback internally
- [ ] Presentation team-wide
- [ ] Possible call(s) to integrate any new changes
- [ ] Restructure pages based on levels of simplicity for contributors, and ease of access to advisers (twb)
- [ ] Add the one-pager from Figma (as it's own page or something that leaves space for it on its own). 
- [ ] Make canned messages for the wider team to use when asked about the program.
- [ ] Decide on acquisition channels (do we use rocketchat pinned message or reddit sidebar....?)
