### ISSUE TITLE
Contributing Section - Contributor Onboarding Guide V2

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#505]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Contributing Section V2 Epic #503 
Working or Proposed Project Doc: Not Started

## Tasks

- [ ] Check for healthy cross-linking, obsolete information, typos
- [ ] Add capitalization details
- [ ] Add new team content on: remote team communication, initiatives "status" heuristics
- [ ] Add new templates, including IA Landing page template: https://hackmd.io/vDXzQC6FQp6bc542_cK_0g
