### ISSUE TITLE
Contributing Section - Earn as a Contributor V2

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#506]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Contributing Section V2 Epic #503 
Working or Proposed Project Doc: Not Started

## Tasks

- [ ] Check for healthy cross-linking, obsolete information, typos
- [ ] Add details when we have more robust bounty system
- [ ] Eventually add a link to a contributor recognition page
- [ ] Revise Find/Approve/Work/Complete section into a "### section format.

**Comment by seamoonm** [comment]
Hi Amy! I've just started working on some version of this now. Anna and I discussed a review of the contributer section with suggestions for UX and onboarding clarity. Might it make sense for us to sync, so that efforts are not doubled, and I'm keeping in mind these bounty requirements as I work? HNY!

**Comment by amy-jung** [comment]
Happy new year! 

Speaking with @annaalexakr on contributor experience as a whole program. Pinged you on rocketchat.

**Comment by seamoonm** [comment]
Hi! Sounds exciting - but I dont see your message on rocketchat? Just a
message from Anna. I was starting to do the review of contributor section
as Anna and I discussed last month, just a few hours in, but will pause
until we can sync and see how I can best support the work!

::
un-cancelling the future
https://linktr.ee/mseamoon

**Comment by seamoonm** [comment]
Oops! Just found the new group you made - pinged you there :)
::
un-cancelling the future
https://linktr.ee/mseamoon
