### ISSUE TITLE
Contributing Section - Contributor Tools Guide V2

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#508]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Contributing Section V2 Epic #503 
Working or Proposed Project Doc: Not Started

## Tasks

- [x] Check for healthy cross-linking, obsolete information, typos
- [x] Simplify content for less technical/new user: 
- [x] [hackmd](https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github) only version
1. "Quick start" version = using github webGUI to submit changes 
2. "Intermediate" = github desktop (current content, possibly re-ordered)
3. "Advanced" = rework some of the text to include/utilize Visual Studio Editor or a similar tool

**Comment by twblack88** [comment]
@amy-jung i slightly edited the list to include Hackmd's push to GH feature.

**Comment by twblack88** [comment]
@andersonmmi gave a huge push on this and got it into the new portal
