### ISSUE TITLE
Maintenance Plan 2020 Epic

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#510]
## Description

Because of the dynamic nature of MakerDAO, many community resources tend to get outdated fairly quickly. In addition, new resources emerging often struggle in the area of discoverability. The solution to this problem is a contributor-based quarterly maintenance plan that tackles fixing general errors and mistakes, renewing outdated resources, improving cross-linking and discoverability of new resources, and more as will be detailed below.

New Project Planning doc (not yet created)
[ OLD Project Planning Doc](https://hackmd.io/Eb3JThoZRgCOeMLi2QYLKQ)

## Issues

- [x] Reestablish Plan for Quarterly Maintenance / #762 
- [x] Recreate SOP/Workflow to incorporate [Hypothesis](https://hypothes.is/) / #762
- [ ] Have a fully contributor-run quarterly maintenance plan for all the resources in the com-dev portal
- [ ] Iterate and improve on the next cycle.

## Milestones

Milestone 1 - Have a community member be the Lead for the maintenance plan.
Milestone 2 - Have a quarter where we don't feel the need to change anything with regards to the plan itself.

**Comment by Davidutro** [comment]
After Portal V1 launches, we will fit a maintenance plan into the quarterly schedule again.
Created an issue for **Reestablishing the Maintenance Plan** | #762 

I have updated the issue to reflect the current state of things.

**Comment by Davidutro** [comment]
Archiving the old schedule, workflow, and process here

## Schedule 2020, TBD

mm/dd/yy - mm/dd/yy | mm/dd/yy - mm/dd/yy | mm/dd/yy - mm/dd/yy | mm/dd/yy - mm/dd/yy
-- | -- | -- | --

## Who Does it

### Initial Pull Request

At the end of each quarter, Leads will find and assign contributors to sections. The contributor will submit work in the form of a Pull Request to the repository listed in their assigned row.

### Review of Pull Requests

The assigned reviewer will go through submitted Pull Requests and mark them reviewed and ready to be merged.

### Merge of Pull Requests

Rich Brown will merge all PRs that are marked reviewed because he has sole access to merging changes into the master branch of the community repository.

## Workflow

1. A week before a maintenance cycle begins a spreadsheet must be set up that lists the grouped sections or individual pages that need to be reviewed, along with special notes if they are necessary. 
   - This is to be done by the project manager of the Maintenance Plan by duplicating the previous quarter’s sheet and updating it for the new cycle.
   - Special notes contain improvement requests, special considerations, “do not change” requests, and virtually anything the person needs to keep in mind when reviewing that row item.
2. The Project Manager is responsible for assigning spots for Owners and Reviewers of each item on the spreadsheet.
   - This gives the PM one week to fill all the spots.
   - The maintenance plan is outlined and shared with the contributor community on the weekly contributor standup call. If spots remain, an ask for more sign-ups is made.
3. Assigned contributors are given access to the spreadsheet by the PM prior to the start of the maintenance cycle sprint.
4. Week one.
   - Owners are asked to complete their Pull Requests by the end of the week and to post the link to them in the spreadsheet.
5. Week two.
   - A set of reviewers go through all their assigned Pull Request and marks them reviewed.
Amy can then merge all the ready Pull Requests.
