### ISSUE TITLE
Contributors Recognition Page in Contributing Section

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#522]
## Description

It's important to have a place in our portal that recognizes contributors in the MakerDAO community for work they've done both inside the portal and outside.

https://allcontributors.org/ is a very interesting option for managing our contributor list.

I've already spoken to Techops and they are willing to implement this on the makerdao/community repo. However, since the filestructure for the /community repo will be changing I will wait before implementing this tool. We are waiting for the new Portal structure; we will add this as a part of the larger portal redesign.

## Tasks

- [x] Task 1 Do some more research into the spec and the next questions we need to ask to move forward with this
- [x] Task 2 Get an agreement about where this page would live.
- [x] Task 3 Specify how this page is added to/maintained.
- [x] Task 4 Define standards for how we invite contributors to be on this page. I argue it should only list contributors who've consented to be listed there.

## Notes

I think the best place for this list is on the landing page of the "Work with us" page. - David

[Sample contributors json file](https://github.com/all-contributors/all-contributors/blob/master/.all-contributorsrc)
[Emoji Key](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)

**Comment by Davidutro** [comment]
Task1:

[Home page](https://allcontributors.org/)
[Install page](https://allcontributors.org/docs/en/bot/installation)

- [ ] We need to agree upon where the contributor page lives.
My vote is that it should live in the [contributor section](https://github.com/makerdao/community/tree/master/contributing) of the comm-dev portal.
> (If you prefer your contributors table in a place other than the README.md; After merging your first bot PR, you can move your contributors table, see files in the [bot configuration](https://allcontributors.org/docs/en/bot/configuration))

**Comment by Davidutro** [comment]
# Task 3
Specify how this page is added to/maintained.

**Comment by Davidutro** [comment]
## Task 4

### Do we ask for consent up front?
I think probably yes, though this includes a lot of overhead.
The alternative is that we remove if asked, but that would leave their info in the version history anyway, so I think probably would want to ask first as a general rule.

**Comment by amy-jung** [comment]
Where the page would show: I would suggest Readme or Contributing Readme
While it looks nice, I'm not 100% convinced this is the best solution, given us having to update it and then the friction around asking for consent. It feels it should be self-driven or captured in the background. But I don't have a better solution so happy to be proven wrong!

**Comment by Davidutro** [comment]
> Where the page would show: I would suggest Readme or Contributing Readme
> While it looks nice, I'm not 100% convinced this is the best solution, given us having to update it and then the friction around asking for consent. It feels it should be self-driven or captured in the background. But I don't have a better solution so happy to be proven wrong!

Contributors _can_ add themselves! :)
Consent will be a question regardless of which solution we use.

**Comment by amy-jung** [comment]
then I think we should make a note in the contributing guide and encourage all contributors to add themselves. "Great work on the onboarding guide! We want to let the world know you made it happen - you can add yourself to our contributors guide :D" or is that weird to get people to add themselves

**Comment by Davidutro** [comment]
I think it's totally acceptable to have people add themselves :)

**Comment by Davidutro** [comment]
## Considerations

Wait for @ryancreatescopy 
- See how this fits given a new content structure.

Do we need a Script/process for getting all the contributors to date?

**Comment by twblack88** [comment]
So on [this page](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73)? 

I like the idea of having a passive list populated based on contributions to the repo. And then the landing page pulling that list from some source. the less overhead the better.

**Comment by amy-jung** [comment]
I think we can start it now with the development since it's pretty fleshed out? @twblack88 where/what week does this align best?

Yup totally agree on the Work with us Page

**Comment by Davidutro** [comment]
Yes, exactly that page.

I think it's a matter of placing the bot in the correct repo and the list in the right .mdx file.
From a development standpoint, I would need to reach out to techops, tell them which repo we want it to live in and where the list should go and they would implement it for us.

**Comment by Davidutro** [comment]
@MaximumCrash implemented this.

Will update with relevant links and instructions after we migrate the repo into makerdao/community

**Comment by twblack88** [comment]
Authors is a custom component you can use on a page showing someone or multiple people wrote it. 

All contributors is integrated into the repo

**Comment by Davidutro** [comment]
@all-contributors please add <Artem Isios Gordon> for <content, Reviewed Pull Requests>

**Comment by Davidutro** [comment]
@all-contributors please add <Artem Isios Gordon> for <Content, Review>

**Comment by Davidutro** [comment]
Questions:

1. Which Emoji Key does our instance of all-contributors point to? Is it [this standard one](https://github.com/all-contributors/all-contributors/blob/master/docs/emoji-key.md)?

2. Can we add custom emoji keys?
- Oh I guess we can, using the config file (see below).

3. I noticed in [community/blob/master/.all-contributorsrc](https://github.com/makerdao/community/blob/master/.all-contributorsrc) a few of the config parameters are missing. Is that intentional?

The config as seen on [this page](https://allcontributors.org/docs/en/bot/configuration) is:

```
{
  "files": ["README.md"],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "contributorsSortAlphabetically": false,
  "badgeTemplate": "[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)",
  "contributorTemplate": "<a href=\"<%= contributor.profile %>\"><img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>",
  "types": {
    "custom": {
      "symbol": "🔭",
      "description": "A custom contribution type.",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
  "skipCi": "true",
  "contributors": []
}
```
While our `.all-contributorsrc` file has:

```
{
  "files": ["README.md"],
  "imageSize": 100,
  "commit": false,
  "contributors": [],
  "contributorsPerLine": 8,
  "projectName": "community-portal",
  "projectOwner": "makerdao",
  "repoType": "github",
  "repoHost": "https://github.com",
  "skipCi": true
}
```

**Comment by Davidutro** [comment]
See Authors compenent on [this page](https://community-development.makerdao.com/en/resources/technical-content/palette-recipes)

Met with Tim:
The tentative plan is to create a branch and test what authors will look like in a few locations. 
Take screenshots
Make a poll in #community-development for where this should be displayed

With regards to populating the list; 
I will add people _with Github accounts_ first
I will then DM Rejon, asking how to manually PR people into the all-contributo.json file (I want to make sure it doesn't screw up the bot that auto-updates the src file).
I am rereading the notes in this [Pull Request](https://github.com/makerdao/community-portal/pull/146) to be a little less ignorant about how this component works with the all-contributor bot.

**Comment by Davidutro** [comment]
Authors is now totally in the hands of the portal team
