### ISSUE TITLE
Review & fix broken links in Contributing Section

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#534]
## Description

The contributing section should improve contributor experience and onboarding. Guides should remove the barriers for community members to be part of the team, improve community resources, give and receive feedback, and grow the MakerDAO community.

Check the [Reviewer's Guide](https://community-development.makerdao.com/contributing/reviewer-guide) before starting work

Working or Proposed Project Doc: Not started

## Tasks

- [ ] Fix relative links in contributor onboarding guide
- [ ] Fix formating issues in each document of the contributing section (look out for italics, headers, etc)
- [ ] Review all links & cross-links in each document of the contributing section

**Comment by amy-jung** [comment]
This will be depreciated by the new portal
