### ISSUE TITLE
Portal Redesign (Content): Map "Learn" content

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#562]
## Description

The "Learn" section is currently the most incomplete section of the site – it's largely built out of lists of FAQs, Awesome MakerDAO content and a sense of what we want to educate users about. Content needs writing, but first we need to have a clear picture of what content already exists as FAQs or on Awesome MakerDAO so we can avoid duplicate work.

[Current Sitemap](https://www.figma.com/file/mVblaaFzkqracWycXl9czh?node-id=638:384)

## Tasks
- [x]  Sitemap is signed off
- [x]  Mapping is signed off and clear to follow for content writers
- [x]  Pages are categorized so that it's clear what kind of content is expected on each page
- [ ]  Content gaps are identified in new GitHub issues

## References
[Awesome MakerDAO](https://www.notion.so/On-Awesome-MakerDAO-f293924675034ec8b7d878437ed5fb27)
["Learn" IA workshop](https://www.notion.so/Learn-workshop-c643ed325a5e43e39d280a8ada0d48f2)

**Comment by amy-jung** [comment]
We decided on a call to have a few examples of #564 content rewritten as context before setting a call w/ other stakeholders to finalize the map

**Comment by twblack88** [comment]
Since the content folder will accommodate any structure it's up to the team to make sure the map is top of mind. I think the IA was planned and then executed in the first week of August (according to roadmap). 

Also FWIW, we can keep archival content and there are plans in the works to migrate or deprecate pages based on an audit. 🙌
