### ISSUE TITLE
Portal Redesign (Dev) EPIC: Architecture

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#563]
## Description

The sandbox is [up and running](https://github.com/makerdao/community-portal) for local development.  Utilizing Gatsby and Dai.Ui there is quite a bit of routing and folder structures to set up and build out. 

## Goals

- [x] Set up site navigation and underlying architecture (including queries, content structure etc.)
- [x] Set up branches ( and admin access @ghettodev ) plug in services
- [x] Build out config files and index files into templates

**Comment by amy-jung** [comment]
@twblack88 can we close this?
