### ISSUE TITLE
Portal Redesign (Content) EPIC: Reformat existing content to new "Learn" formats

### ISSUE THREAD

**Issue by amy-jung** [makerdao/community#564]
## Description

The new "Learn" mapping (#562 ) will give us some raw content and important sections, but we'll still need to write things like introductions and think about related content so we can cross-link between pages effectively.

[List of Content to Reformat](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit?usp=sharing)

## Acceptance criteria

- [ ]  New content is signed off
    - [ ]  Meet style requirements
    - [x]  No dead-ends (relevant onward links)
    - [x]  Have clear intros
    - [ ]  Low readability scores etc

## References
[Content Design Guide](https://www.notion.so/Content-design-guide-ec389e89a9264ba2b206873f8f3aa714)
["Learn" Intro Page (example: Dai)](https://www.notion.so/Learn-intro-page-example-Dai-8d6093b9ee5043f2ac9e76094af78446)
["Learn" Sub-topic Page (example: Dai Savings Rate)](https://www.notion.so/Learn-sub-topic-page-example-governance-polls-8cf8021bb0c943ffa5ff8f87daaaa6bb)
["Learn" Tutorial/Guide (example: How to use Dai)](https://www.notion.so/Learn-tutorial-guide-page-example-how-to-participate-in-voting-bdbe550197354d22962bca7de49feef7)

**Comment by amy-jung** [comment]
A majority of this work may be done in MD using a template developed by dev team.

Depending on development, we can fold in this or may have to create a new epic: Creating the pages. Thoughts from @ryancreatescopy : 

I'd recommend working in a CMS as much as possible but understand that this might not be possible due to the dev work happening concurrently with this phase of the project. So it may be necessary to include an epic that covers:

- adding the content to the site (whether that's via PRs or ???)
- editorialising the content using the new components being built

**Comment by twblack88** [comment]
I think this is complete.
