### ISSUE TITLE
Portal Redesign (Dev) EPIC: Templates

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#566]
## Description

Working off of the template pages in [Ryan's Figma](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=294%3A474)

We'll build up template mdx files and as a result have documentation to use them, That documentaiton will also be an mdx file. 

## First Templates 

- [x] Documentation of available components and building a page
- [x] [Work with us](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A13)
- [x] [Funding](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=398%3A0)

### References for copy
[Work with us Gitbook](https://ryancordell.gitbook.io/comm-de/work-with-us)
[funding gitbook](https://ryancordell.gitbook.io/comm-de/funding)

**Comment by amy-jung** [comment]
@twblack88 can we close this?

**Comment by twblack88** [comment]
Oy vey i mised this notification! Absolutely.
