### ISSUE TITLE
Portal Redesign (Dev) EPIC: Components

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#567]
## Description

Creating pages is going to be straightforward with a list of available components for content creators. 

### Reference
[Components page](https://www.notion.so/Components-e4455d1797f74c48aae3019692a39413)

#### Components list
This list is semi- prioritized. For full spec and discussion see the project board in the Sandbox repo. 
- [ ] Page Heading
- [ ] Breadcrumbs
- [ ] Code syntax
- [ ] Links
- [ ] Tabs
- [ ] CTA's
- [ ] Callout
- [ ] Status alert
- [ ] Touts
- [ ] 3 column chocolate box (learn content and Governance content are good examples)
- [ ] Categories
- [ ] 2- Column
- [ ] Process list
- [ ] Lists
- [ ] Checklists
- [ ] Accordian
- [ ] Info blocks (image + copy)
- [ ] Progressive disclosure (E.g., "show 10 more topics")
- [ ] Image
- [ ] Inline video 
- [ ] Multi video
- [ ] Inline GIF
- [ ] Alternative Header

##### Nice to have
Subject to opening another issue and a discussion about if it's possible. Perhaps we can iframe in components from the mkrgov dash and transparency dash when appropriate. 
- iFrame of mkrgov.science
- iFrame of transparency Dash

**Comment by twblack88** [comment]
These were prioritized and developed in the soft launch.
