### ISSUE TITLE
CDIP 25- Badges forum delivery 

### ISSUE THREAD

**Issue by twblack88** [makerdao/community#636]
## Description

CDIP 15 exhausted it's budget due to the enormous complexity of DIscourse's backend. On top of it being kind of a pain all their documentation is, 😒 , written on discourse in forum format. 

[This is the CDIP plan as scoped](https://docs.google.com/document/d/1D98hrtTxcGFbcSR55yfMQtS72e4MOATc1QJSTbnuuhM/edit#heading=h.ktbfbk9aggt4)
You can find the [project board for the staging forum.](https://github.com/andersonmmi/3box-discourse-theme-component/projects/1) Included are the new developers that have ramped up to solve this problem.

## Tasks

Community Members have requested badges for their activity in the Maker Ecosystem. Badges are already implemented in the forum, but they are limited to interactions within the forum. Badges gamify community engagement and have proven successful on platforms like Xbox Live, Playstation Network, Steem, Uber, AirB&B, and government agency services.

In order for Maker Ecosystem badges to be displayed in forums, a web3 integration must be implemented in order for the forum server to map a user to an Ethereum address(es) and to read badge data from on-chain. The concept will be proven with CDIP-18 NFTs which are nearing mainnet.

Subtasks include:

- [x] Establish DevOps and workflows 
- [x] Onboard additional developers 
- [x] Install a web3 Ruby gem and a web3 JavaScript package to the staging-forum source code 
- [x] Ramp up Jim as a contributing Dev and Elijah for web3 tasks.
- [x] [create a forum badge for holding a "Vote on a governance poll" NFT badge](https://github.com/andersonmmi/3box-discourse-theme-component/issues/11) 
- [x] Feature: [if the user logs in, and they are not mapped to an address, notify them through Discobot ](https://github.com/andersonmmi/3box-discourse-theme-component/issues/10)
- [x] Feature: [the user signs a message on the front-end proving that they control a given private key](https://github.com/andersonmmi/3box-discourse-theme-component/issues/9) 
- [x] Feature: [the server maps the signed message to the user’s record in the database](https://github.com/andersonmmi/3box-discourse-theme-component/issues/4) 
- [x] Feature: [the server queries the chain for badge data at the associated address](https://github.com/andersonmmi/3box-discourse-theme-component/issues/3) 
- [x] Feature:[ the server updates the user’s record with badge data](https://github.com/andersonmmi/3box-discourse-theme-component/issues/1) 
- [x] [Create an admin interface that allows the addition of Badges and Links them to on chain badge tokens ](https://github.com/andersonmmi/3box-discourse-theme-component/issues/13)
- [x] [Feature: the front-end renders badges on the user’s profile](https://github.com/andersonmmi/3box-discourse-theme-component/issues/2) 
- [x] [Feature: user can add additional address to unlock badges at those addresses](https://github.com/andersonmmi/3box-discourse-theme-component/issues/5) 
- [x] [Create documentation to describe how to apply this function to CDIP-18](https://github.com/andersonmmi/3box-discourse-theme-component/issues/7) 
- [x] [Demonstrate functionality on a Comm-Dev call](https://github.com/andersonmmi/3box-discourse-theme-component/issues/8)
