### ISSUE TITLE
Portal Redesign (Content) EPIC: Review content for Learn Section of "Dai"

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#679]
## Description
Suggested content already exists in the [MCD Dai FAQ](https://github.com/makerdao/community/blob/master/faqs/dai.md). The content team should review these pages against what exists.

[Link to range in Content Sprint Spreadsheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=48:54)

## Steps
1. Review [Writing Style Guide](https://community-development.makerdao.com/contributing/writing-style-guide)
2. [View the Portal Content Sprint Spreadsheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0)
3. Work in hackmd (for comments/suggested edits) (We’ll be skipping google docs)
      - View [prototype](https://www.figma.com/file/mVblaaFzkqracWycXl9czh/Maker-comm-dev?node-id=355%3A73) to get a sense of end goal
      - Make sure content fits Page Template model ([Linked in google sheet](https://docs.google.com/spreadsheets/d/1nk3fCBEIstY_wkSBvZReEPjBzm2GOXEGpeLDEZWrhcI/edit#gid=0&range=B1))
      - Compare [old content](https://community-development.makerdao.com/) with new content (look for any missing holes)
      - Check for any outdated information
4. Run edits through a spell checker

**Acceptance criteria**

- [ ]  No missing content (these pages should include all necessary content from the existing site)
    - Reviewers should note that if content appears missing it has probably been left out deliberately. Consider what the user is trying to do an ask yourself whether it's needed or whether it just adds clutter to the page.
    - Any missing content should be turned into a new GitHub issue
- [ ]  Information is accurate
- [ ]  Language/terminology meets expectations
- [ ]  Links are correct

**Comment by TomDeMichele** [comment]
Get and Use Dai pages updated, used the content from the guide.

**Comment by TomDeMichele** [comment]
Also got rid of spend Dai and included the spend info in the use page.

**Comment by HaydenSander** [comment]
Fixed links, changed icons, and added a more relevant "related section" to the bottom of the page for index.mdx. Fixed a link within the DSR page.

**Comment by twblack88** [comment]
I pushed a slight edit on the DAI pages too today. Making language cleaner and more accessible .

**Comment by Davidutro** [comment]
Since all content is frozen, I am closing this issue.

Further work on the Learn pages, and other portal pages, will be done as part of maintenance.
