### ISSUE TITLE
Research Speaker Grants addition to Meetup Grants program.

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#786]
## Description

As a result of feedback recieved from community leads and meetup organizers, it may be a good idea to establish a funding flow for speakers at these meetups. There is a lot to think about so this issue is just for the research bit.

No Working doc yet.

## Tasks

- [ ] Task 1 / Establish possible issues
- [ ] Task 2 / Figure out feasibility, given the Maker Foundation's planned deprecation.
- [ ] Task 3 / Figure out how to integrate Meetup Grants and Speaker Grants for simplicity since they overlap.

**Comment by Davidutro** [comment]
This was never done, leaving it to whoever relaunches Meetup grants
