### ISSUE TITLE
Public Call Summary Team Epic

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#826]
## Description

This is the Epic to house all sub-issues related to the summary team at MakerDAO.
The Summary Team produces high-quality summaries and shortened "snippets" of public calls that happen at MakerDAO.

## Purpose

- 

## Important Links

[GnR summary guide](https://community-development.makerdao.com/en/contribute/governance_and_risk_meetings/summaries)
[Hackmd Team Workspace](https://hackmd.io/team/govsummaries?nav=overview)
[Call Participation Signup Sheet](https://hackmd.io/rfCkJrKwSUel2A_SozfM3A?edit)

## Goals

- [ ] Grow team to be 6 active writers per month (currently 3)
- [x] Train Artem Gordon to be the second QA
- [ ] Find the right place for the summaries in the community development portal. (Should they even be in the community development portal?) / 

## Bounties

Writer role earns 30 Dai per hour.
Reviewer role earns 40 Dai per hour.

## Interested?

Join the [#gov-call-summaries](https://chat.makerdao.com/channel/gov-call-summaries) channel and express interest!

**Comment by Davidutro** [comment]
all of this is handled off GH, retiring this epic
