### ISSUE TITLE
Do we want to keep producing high-fidelity summaries of public calls?

### ISSUE THREAD

**Issue by Davidutro** [makerdao/community#839]
## Description

With the introduction of [Snippets](https://forum.makerdao.com/t/agenda-discussion-scientific-governance-and-risk-112-thursday-october-1-16-00-utc/4391/5), which are low-latency, brief summaries of public calls, the need for a [high-quality summary](https://forum.makerdao.com/t/agenda-discussion-scientific-governance-and-risk-111-thursday-september-24-16-00-utc/4239/2) comes into question.

High-quality summaries include a number of things that snippets don't. Listed:
- Time-anchored links
- Screenshots of presentations
- Semi-transcribed segments and discussions of the entire call.

Snippets offer a different set of advantages. Listed:
- Low turnaround time (posted same day)
- Focused on only the main points that happen throughout the call.

I'm sure if I spent a little more time, more can be added to these lists. However, for the sake of time and just getting this idea out there, I will leave it there for now.

We now have two different summary formats. It's our job to answer the question of when to use which, and whether the cost of producing the higher-fidelity summary is worth it.

## Tasks

- [ ] Task 1 / Talk to the Gov-comms working group about this issue.
- [ ] Task 2 / Create a better pros and cons matrix.
- [ ] Task 3 / Create Forum Post and Poll about the readership and usefulness of these summaries

**Comment by Davidutro** [comment]
Idea: write forum thread polling for interest in high fidelity summaries vs snippets

**Comment by Davidutro** [comment]
https://forum.makerdao.com/t/discussion-are-high-fidelity-summaries-of-governance-calls-useful-would-you-vote-to-fund-them/4927

Answer: Yes, they are useful, important, and worth funding.
